// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R6.Core.Enums;
using R6.Infra.Context;

#nullable disable

namespace R6.Infra.Migrations
{
    [DbContext(typeof(R6Context))]
    [Migration("20220330161059_AddGunTable")]
    partial class AddGunTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "armor_type", new[] { "light", "medium", "heavy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dificult_type", new[] { "easy", "medium", "hard" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "primary_gun_type", new[] { "smg", "ar", "lmg" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "secondary_gun_type", new[] { "hand_gun", "machine_pistol", "shotgun" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "speed_type", new[] { "slow", "medium", "fast" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R6.Domain.Entities.Gun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PrimaryGunType?>("PrimaryGunType")
                        .HasColumnType("primary_gun_type");

                    b.Property<SecondaryGunType?>("SecondaryGunType")
                        .HasColumnType("secondary_gun_type");

                    b.Property<long>("operatorId")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("operatorId")
                        .IsUnique();

                    b.ToTable("Gun");
                });

            modelBuilder.Entity("R6.Domain.Entities.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<ArmorType>("Armor")
                        .HasColumnType("armor_type")
                        .HasColumnName("Armor");

                    b.Property<DificultType>("Dificult")
                        .HasColumnType("dificult_type")
                        .HasColumnName("Dificult");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Name");

                    b.Property<SpeedType>("Speed")
                        .HasColumnType("speed_type")
                        .HasColumnName("Speed");

                    b.HasKey("Id");

                    b.ToTable("Operator", (string)null);
                });

            modelBuilder.Entity("R6.Domain.Entities.Gun", b =>
                {
                    b.HasOne("R6.Domain.Entities.Operator", "Operator")
                        .WithOne("Gun")
                        .HasForeignKey("R6.Domain.Entities.Gun", "operatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("R6.Domain.Entities.Operator", b =>
                {
                    b.Navigation("Gun")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
